### ISSUE TITLE
Test bounty issue

### ISSUE THREAD

**Issue by geido** [Superset-Community-Partners/superset#15]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ciphx** [comment]
hello, can i be assigned this issue? or do I need to add an implementation comment first?

**Comment by sshdopey** [comment]
Is this actually a bounty???

I thin it was being used to test creating bounties. should be lcosed by now  though.

**Comment by ghost** [comment]
@geido > Lemme Know if this issue is up for grab - assign to me!

**Comment by geido** [comment]
This was clearly a test issue as the title suggests and the absence of any description. I am closing it...
